# A confidential OAuth2 application. The client secret is generated by the API
# on creation and exposed as a sensitive computed attribute.
resource "wellplayed_organization_app" "web" {
  name              = "Acme Web"
  description       = "Acme web application."
  short_description = "Acme web."
  icon              = "https://cdn.example.com/acme.png"

  redirect_urls        = ["https://play.example.com/auth/callback"]
  logout_redirect_urls = ["https://play.example.com/"]
  login_url            = "https://play.example.com/login"
  consent_url          = "https://play.example.com/consent"
  requires_consent     = true
}

# A public OAuth2 client (e.g. a SPA or mobile app) with no client secret.
resource "wellplayed_organization_app" "spa" {
  name        = "Acme SPA"
  description = "Acme single-page app."
  public      = true

  redirect_urls        = ["https://app.example.com/callback"]
  logout_redirect_urls = ["https://app.example.com/"]
  login_url            = "https://app.example.com/login"
  consent_url          = "https://app.example.com/consent"
  requires_consent     = false
}

# The generated client secret (confidential clients only).
output "web_client_secret" {
  value     = wellplayed_organization_app.web.secret
  sensitive = true
}
